modLoader = "kotlinforforge"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "HuHoBot"
authors = "HuoHuas001"
description = '''
HuHoBot for Forge enabling the official QQ bot to connect to your server.
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version},)"
ordering = "AFTER"
side = "BOTH"